#!/bin/bash

set -e

OPENSSL_VERSION="1.1.1f"

SCRIPT_DIR="$(dirname $(realpath $0))"
TROJAN="${SCRIPT_DIR}"
. "$TROJAN/env"
CWD="${SCRIPT_DIR}/android-openssl"
TROJAN="$(dirname "$CWD")"
mkdir -p "$CWD"/{build,out}

cd "$CWD/build"
if [[ ! -f openssl-$OPENSSL_VERSION.tar.gz ]];then
  wget https://openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz
fi
if ! [[ -d openssl-$OPENSSL_VERSION ]];then
  tar xf openssl-$OPENSSL_VERSION.tar.gz
  pushd openssl-$OPENSSL_VERSION
  # make distclean
  ./Configure android-x86_64 -D__ANDROID_API__=21 no-shared no-ssl2 no-ssl3 no-unit-test --prefix="$CWD/out"
  popd
else
  # assume src is already configured and is ready to make
  : rm -rf openssl-$OPENSSL_VERSION
fi

cd "openssl-$OPENSSL_VERSION"
make depend
make
make install_sw
cd "$CWD/out"
install -Dvm644 include/openssl/opensslconf.h $TROJAN/igniter/app/src/main/cpp/libs/lib/x86_64/openssl/opensslconf.h
install -Dvm644 lib/libcrypto.a $TROJAN/igniter/app/src/main/cpp/libs/lib/x86_64/libcrypto.a
install -Dvm644 lib/libssl.a $TROJAN/igniter/app/src/main/cpp/libs/lib/x86_64/libssl.a
