#!/usr/bin/env bash

SCRIPT_DIR="$(dirname $(realpath $0))"
TROJAN="${SCRIPT_DIR}"
. "$TROJAN/env"
IGNITER="${SCRIPT_DIR}/igniter"
cd "${IGNITER}"
cp -r ../patch/igniter/* .
./gradlew assembleRelease
find . -name '*.apk' | xargs -L1 realpath
