#!/usr/bin/env bash
SCRIPT_DIR="$(dirname $(realpath $0))"
TROJAN="${SCRIPT_DIR}"
. "$TROJAN/env"
cd $SCRIPT_DIR/android-boost
cp ../patch/android-boost/* .

ARCH="${ARCH:-x86_64}"

lib_program_options(){
  echo -n "$(realpath $(find "./build/out/$(todir ${ARCH})/lib/" -name 'libboost_program_options*.a'))"
}

lib_system(){
  echo -n "$(realpath $(find "./build/out/$(todir ${ARCH})/lib/" -name 'libboost_system*.a'))"
}

echo "$(lib_program_options)"
echo "$(lib_system)"

if [[ -f "$(lib_program_options)" ]] && [[ -f "$(lib_system)" ]]; then
  # skip if already exists
  :
else
  ./build-android.sh --arch="$(todir ${ARCH})" --with-libraries=program_options,system "${ANDROID_NDK}"
fi

install -Dvm644 "$(lib_program_options)" "$TROJAN/igniter/app/src/main/cpp/libs/lib/$(todir ${ARCH})/libboost_program_options.a"
install -Dvm644 "$(lib_system)" "$TROJAN/igniter/app/src/main/cpp/libs/lib/$(todir ${ARCH})/libboost_system.a"

# git checkout ./build-android.sh
