#!/usr/bin/env bash

set -e

OPENSSL_VERSION="1.1.1e"
# ARCH=arm
# ARCH=arm64
# ARCH=x86
# ARCH=x86_64
ARCH="${ARCH:-x86_64}"

SCRIPT_DIR="$(dirname $(realpath $0))"
TROJAN="${SCRIPT_DIR}"
. "$TROJAN/env"
CWD="${SCRIPT_DIR}/android-openssl"
TROJAN="$(dirname "$CWD")"
mkdir -p "$CWD"/{build,out/$ARCH}

cd "$CWD/build"
if [[ ! -f openssl-$OPENSSL_VERSION.tar.gz ]];then
  wget https://openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz
fi
if ! [[ -d openssl-$ARCH-$OPENSSL_VERSION ]];then
  mkdir -p openssl-$ARCH-$OPENSSL_VERSION
  tar -C openssl-$ARCH-$OPENSSL_VERSION -xf openssl-$OPENSSL_VERSION.tar.gz --strip=1
  pushd openssl-$ARCH-$OPENSSL_VERSION
  # make distclean
  ./Configure android-"${ARCH}" -D__ANDROID_API__=21 no-shared no-ssl2 no-ssl3 no-unit-test --prefix="$CWD/out/$ARCH"
  popd
else
  # assume src is already configured and is ready to make
  : rm -rf openssl-$OPENSSL_VERSION
fi

cd "openssl-$ARCH-$OPENSSL_VERSION"
make depend
make
make install_sw
cd "$CWD/out/$ARCH"
install -Dvm644 include/openssl/opensslconf.h $TROJAN/igniter/app/src/main/cpp/libs/include/"$(todir ${ARCH})"/openssl/opensslconf.h
install -Dvm644 lib/libcrypto.a $TROJAN/igniter/app/src/main/cpp/libs/lib/"$(todir ${ARCH})"/libcrypto.a
install -Dvm644 lib/libssl.a $TROJAN/igniter/app/src/main/cpp/libs/lib/"$(todir ${ARCH})"/libssl.a
